In [4]:
import torch
import numpy as np

In [21]:
tmp_actions = torch.rand(5,4,3)
tmp_inv = torch.rand(5,3,1)

In [22]:
out = torch.matmul(tmp_actions, tmp_inv)
out.shape

torch.Size([5, 4, 1])

In [5]:
tmp = torch.rand(5,4)

In [8]:
torch.cat([tmp, tmp], dim=0)

tensor([[0.1695, 0.9479, 0.2903, 0.2508],
        [0.8729, 0.6058, 0.7336, 0.8563],
        [0.0457, 0.5836, 0.6030, 0.1667],
        [0.3851, 0.7661, 0.9269, 0.9407],
        [0.5851, 0.1644, 0.3070, 0.4075],
        [0.1695, 0.9479, 0.2903, 0.2508],
        [0.8729, 0.6058, 0.7336, 0.8563],
        [0.0457, 0.5836, 0.6030, 0.1667],
        [0.3851, 0.7661, 0.9269, 0.9407],
        [0.5851, 0.1644, 0.3070, 0.4075]])

In [7]:
tmp[0:0+1,:]

tensor([[0.1695, 0.9479, 0.2903, 0.2508]])

In [3]:
torch.rand(5,4).numpy()

array([[0.64801466, 0.4984494 , 0.76076186, 0.19821471],
       [0.8465361 , 0.7396556 , 0.4589194 , 0.5045494 ],
       [0.16229212, 0.43178177, 0.8064408 , 0.6909523 ],
       [0.94091606, 0.45656615, 0.5283224 , 0.9391731 ],
       [0.02857065, 0.62020016, 0.14466685, 0.77957183]], dtype=float32)

In [12]:
torch.rand(2,).unsqueeze(dim=1)

tensor([[0.5005],
        [0.5142]])

In [18]:
torch.rand(5,4)[0:2, 0:2]

tensor([[0.0487, 0.6535],
        [0.2671, 0.7648]])

In [24]:
torch.randint(low=0, high=9, size=(5,4)).numpy().dtype

dtype('int64')

In [25]:
torch.randint(low=0, high=9, size=(9,))

tensor([8, 7, 5, 6, 2, 8, 2, 6, 8])

In [32]:
torch.cat([
    torch.randint(low=0, high=9, size=(9,)).unsqueeze(0),
    torch.randint(low=0, high=9, size=(9,)).unsqueeze(0)
], dim=0)

tensor([[7, 4, 5, 7, 5, 7, 0, 7, 5],
        [0, 0, 3, 5, 7, 7, 3, 8, 6]])

In [31]:
torch.randint(low=0, high=9, size=(9,)).unsqueeze(0)

tensor([[6, 6, 4, 2, 6, 8, 5, 4, 4]])

In [1]:
import torch

In [3]:
torch.embedding.__file__

AttributeError: 'builtin_function_or_method' object has no attribute '__file__'