In [28]:
import torch
import torch.functional as F

from torch.nn import Embedding

In [19]:
batch_inv = torch.randint(low=0,high=20,size=(5,4))
batch_inv

tensor([[14,  6, 17, 19],
        [12,  9,  9,  9],
        [16, 11, 17, 11],
        [ 8, 15,  4,  0],
        [ 4, 13,  9, 13]])

In [20]:
fixed_mask = batch_inv >= 10
fixed_mask

tensor([[ True, False,  True,  True],
        [ True, False, False, False],
        [ True,  True,  True,  True],
        [False,  True, False, False],
        [False,  True, False,  True]])

In [21]:
fixed_copy = batch_inv.clone()
fixed_copy[fixed_mask] = 0
fixed_copy

tensor([[0, 6, 0, 0],
        [0, 9, 9, 9],
        [0, 0, 0, 0],
        [8, 0, 4, 0],
        [4, 0, 9, 0]])

In [25]:
~fixed_mask

tensor([[False,  True, False, False],
        [False,  True,  True,  True],
        [False, False, False, False],
        [ True, False,  True,  True],
        [ True, False,  True, False]])

In [35]:
flex_copy = batch_inv.clone()
flex_copy[~fixed_mask] = 10
flex_copy

tensor([[14, 10, 17, 19],
        [12, 10, 10, 10],
        [16, 11, 17, 11],
        [10, 15, 10, 10],
        [10, 13, 10, 13]])

In [36]:
flex_copy-10

tensor([[4, 0, 7, 9],
        [2, 0, 0, 0],
        [6, 1, 7, 1],
        [0, 5, 0, 0],
        [0, 3, 0, 3]])

In [31]:
flex_weight = torch.rand(10,13)
flex_weight

tensor([[0.3420, 0.7614, 0.9955, 0.5311, 0.3043, 0.5155, 0.6642, 0.2290, 0.6179,
         0.6790, 0.8215, 0.3826, 0.3912],
        [0.9008, 0.4130, 0.5577, 0.0614, 0.0099, 0.7767, 0.2097, 0.2365, 0.4391,
         0.3240, 0.1906, 0.6112, 0.4378],
        [0.6848, 0.3371, 0.7926, 0.0330, 0.5671, 0.7052, 0.7922, 0.5666, 0.5071,
         0.0118, 0.8746, 0.1881, 0.2337],
        [0.7446, 0.0940, 0.0045, 0.9732, 0.8849, 0.3228, 0.8750, 0.2587, 0.2081,
         0.8355, 0.2859, 0.1429, 0.2595],
        [0.0772, 0.6965, 0.0908, 0.5476, 0.1248, 0.1615, 0.7567, 0.6785, 0.4268,
         0.3875, 0.7127, 0.2633, 0.7720],
        [0.0825, 0.5535, 0.7698, 0.2817, 0.3759, 0.8157, 0.9447, 0.3344, 0.3152,
         0.8779, 0.9034, 0.3291, 0.8548],
        [0.6054, 0.3469, 0.1841, 0.5090, 0.8071, 0.3714, 0.8342, 0.1941, 0.5893,
         0.5650, 0.7051, 0.8628, 0.1596],
        [0.5792, 0.9121, 0.7769, 0.3200, 0.5750, 0.3594, 0.0044, 0.6752, 0.7962,
         0.6210, 0.5515, 0.7893, 0.4421],
        [0.3792,

In [29]:
fixed_embedding = Embedding( num_embeddings=10, embedding_dim=13, padding_idx=0 )

In [37]:
torch.nn.functional.embedding( 
    input=flex_copy-10, weight=flex_weight, padding_idx=0, 
    max_norm=fixed_embedding.max_norm, norm_type=fixed_embedding.norm_type,
    scale_grad_by_freq=fixed_embedding.scale_grad_by_freq, sparse=fixed_embedding.sparse,
)

tensor([[[0.0772, 0.6965, 0.0908, 0.5476, 0.1248, 0.1615, 0.7567, 0.6785,
          0.4268, 0.3875, 0.7127, 0.2633, 0.7720],
         [0.3420, 0.7614, 0.9955, 0.5311, 0.3043, 0.5155, 0.6642, 0.2290,
          0.6179, 0.6790, 0.8215, 0.3826, 0.3912],
         [0.5792, 0.9121, 0.7769, 0.3200, 0.5750, 0.3594, 0.0044, 0.6752,
          0.7962, 0.6210, 0.5515, 0.7893, 0.4421],
         [0.7519, 0.5183, 0.9642, 0.5317, 0.5886, 0.1216, 0.5157, 0.7008,
          0.6318, 0.6181, 0.5566, 0.3205, 0.4566]],

        [[0.6848, 0.3371, 0.7926, 0.0330, 0.5671, 0.7052, 0.7922, 0.5666,
          0.5071, 0.0118, 0.8746, 0.1881, 0.2337],
         [0.3420, 0.7614, 0.9955, 0.5311, 0.3043, 0.5155, 0.6642, 0.2290,
          0.6179, 0.6790, 0.8215, 0.3826, 0.3912],
         [0.3420, 0.7614, 0.9955, 0.5311, 0.3043, 0.5155, 0.6642, 0.2290,
          0.6179, 0.6790, 0.8215, 0.3826, 0.3912],
         [0.3420, 0.7614, 0.9955, 0.5311, 0.3043, 0.5155, 0.6642, 0.2290,
          0.6179, 0.6790, 0.8215, 0.3826, 0.3912]